### ISSUE TITLE
TF Acceptance Tests

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#165]
Currently the integration tests with the docker compose using the Materialize image only does `apply` -> `plan` -> `destroy`. It would be good to also tests applicable updates and have a flow of: `apply` -> `plan` -> `update` -> `plan` -> `destroy`.

**Comment by benesch** [comment]
Noticed this this weekend while I was working on #176. Terraform has a builtin acceptance test framework that I think we should use! I put up #177 for review.

**Comment by dehume** [comment]
Remaining resources that will need acceptance tests after https://github.com/MaterializeInc/terraform-provider-materialize/pull/177 is merged.

Resource | Create | Delete | Update | Assigned | Notes |
| --- | --- | --- | --- | --- | --- |
| Cluster | X | X | | Done | Implemented with https://github.com/MaterializeInc/terraform-provider-materialize/pull/177
| Cluster Replica | X | X | X | @dehume | Implemented with https://github.com/MaterializeInc/terraform-provider-materialize/pull/177 (needs Update) |
| Connection AWS Privatelink |  X | X | X | @dehume |
| Connection Confluence Schema |  X | X | X | @dehume |
| Connection Kafka |  X | X | X | @dehume |
| Connection Postgres |  X | X | X | @dehume |
| Connection SSH Tunnel |  X | X | X | @dehume |
| Database |  X | X | | @dehume |
| Index | X | X | | @dehume |
| Materialized View | X | X | X | @bobbyiliev |
| Schema | X | X | | @bobbyiliev |
| Secret | X | X | X | Done | Implemented with https://github.com/MaterializeInc/terraform-provider-materialize/pull/177 |
| Sink Kafka | X | X | X | @bobbyiliev |
| Source Kafka | X | X | X | @bobbyiliev |
|Source Load Generator | X | X | X | @bobbyiliev |
| Source Postgres |  X | X | X | @bobbyiliev |
| Table | X | X | X | @bobbyiliev |
| Type | X | X | | @bobbyiliev |
| View | X | X | X | @bobbyiliev |

**Comment by dehume** [comment]
Will be covered in two PRs:
* https://github.com/MaterializeInc/terraform-provider-materialize/pull/200
* https://github.com/MaterializeInc/terraform-provider-materialize/pull/201
