### ISSUE TITLE
Integration Testing Framework

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#17]

**Comment by benesch** [comment]
Wanted to forward on a sentiment from [this comment on `mz`](https://github.com/MaterializeInc/materialize/issues/16989#issuecomment-1427380348)!

> Tests, tests, tests. We need to start integration testing this thing ASAP! I want us to get to a place where we basically never land a change to mz that doesn't involve either fixing or adding a test. mzcompose is probably the right tool here, since otherwise writing tests againsts CLI is very difficult.

Unfortunately you won't be able to use `mzcompose` in this repository, so you'll have to do something more clever. 

One easy option is to run the `materialize/materialized` Docker image, and teach the Terraform provider about a secret option to use a local endpoint, or something like that. That's probably how 95% of the integration tests want to work. You could even run them in parallel, by running multiple Materialize Docker images.

Then you only need to hit real Materialize Cloud for the enable/disable region and app password resources, which seems totally reasonable. There are only going to be a few of those types of resources.
