### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#238]
Need to improve error handling for resources

> For the future, it might be nice to expose the transport errors and similar when TF_LOG=DEBUG. Have more verbose errors would allow us to be a little more self service when it comes to connection errors.

**Comment by benesch** [comment]
Don't think there's anything more the TF provider needs to do here! It's already doing the right thing. We need to improve things on the database side (https://github.com/MaterializeInc/materialize/issues/12465). Feel free to reopen if you disagree.
