### ISSUE TITLE
Secrets/Strings Parameters

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#25]
Certain resources can reference secrets or use strings for parameter values. For example when creating a [postgres connection](https://materialize.com/docs/sql/create-connection/#postgres) you can specify `SSL CERTIFICATE` either way. The SQL this translates to will change depending on the parameter type, using a secret will prepend `SECRET`.

For our resource parameters than can be configured both ways, we should have the same interface if users use a string or a resource reference.
```
ssl_certificate = "string"
```
or
```
ssl_certificate = materialize_secret.my_secret.name
```
Should both work.

**Comment by benesch** [comment]
Does Terraform support fields that can take different types of objects like that? The way I've usually seen this done in Terraform resources is to have two separate fields:

```hcl
ssl_certificate = "literal string"
ssl_certificate_secret = <secret ref>
```

where the provider then enforces that you set one or the other, but not both.

One additional wrinkle here: referring to a secret in Terraform land is hard! The way the e.g. Snowflake provider handles object references is to take the database, schema, and name as three separate parameters. See, for example, the [`snowflake_table`](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/table_grant) resource. The way that would look here is (brace yourself):

```hcl
ssl_certificate = "literal string"
# OR
ssl_certificate_secret_database_name = "db"
ssl_certificate_secret_schema_name = "schema"
ssl_certificate_secret_name = "sekret"
```

I can't see a way to do it with a single `ssl_certificate_secret` field name that doesn't have a bunch of pitfalls around identifier quoting.
