### ISSUE TITLE
Remove `Ownership` from Cluster Replicas

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#257]
Error with [acceptance tests](https://github.com/MaterializeInc/terraform-provider-materialize/actions/runs/5705824876/job/15460893030) in the automated build around cluster replicas.

```
Error: ERROR: altering the owner of a cluster replica is not supported (SQLSTATE XX000)
```

I seems we need to remove `ownership` from the [cluster replica resource](https://github.com/MaterializeInc/terraform-provider-materialize/blob/main/pkg/resources/resource_cluster_replica.go#L51).

**Comment by benesch** [comment]
Ah, yep, looks like fallout from https://github.com/MaterializeInc/materialize/issues/20792.
