### ISSUE TITLE
Hide Numbered Sizes Outside Testing

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#266]
Currently users can see the numbered sizes (intended for running against the image). Better to limit those options to just testing. 

![Screenshot 2023-08-08 at 10 18 31 AM](https://github.com/MaterializeInc/terraform-provider-materialize/assets/7467658/068ea0d2-3dcd-4c32-9e70-cadd248f5af9)

**Comment by benesch** [comment]
Linking in an idea from Slack: https://materializeinc.slack.com/archives/C04UXQZALES/p1691517281263879?thread_ts=1691511655.644279&cid=C04UXQZALES

tl;dr is that we can create a `bin/materialized` script that runs (pseudocode)

```
-- The specific allocations don't actually matter; just need the sizes to exist
-- and exactly match what we run with in production.
docker run materialized:v0.x.y \
  --cluster-replica-sizes="{
    \"3xsmall\": {\"workers\": 1, \"scale\": 1, \"credits_per_hour\": \"1\"},
    \"2xsmall\": {\"workers\": 1, \"scale\": 1, \"credits_per_hour\": \"1\"},
    \"xsmall\": {\"workers\": 1, \"scale\": 1, \"credits_per_hour\": \"1\"},
    \"small\": {\"workers\": 1, \"scale\": 1, \"credits_per_hour\": \"1\"}
  }" \
  --bootstrap-default-cluster-replica-size=3xsmall \
  --bootstrap-builtin-cluster-replica-size=3xsmall
```

and then use that during local dev of the provider and in CI. That way the local version of Materialize will have the same sizes that exist in production, and we won't need to teach Terraform about `1`, `2`, etc.
