### ISSUE TITLE
Escape all identifiers and values

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/terraform-provider-materialize#27]
## Problem

As far as I can tell, the provider today does not do any escaping of identifiers or values. User-provided values are simply splatted directly into the SQL queries:

https://github.com/MaterializeInc/terraform-provider-materialize/blob/6eaca94205bd2190dd5795c87d5d8f0e77ed2fd7/materialize/resources/resource_cluster.go#L50

https://github.com/MaterializeInc/terraform-provider-materialize/blob/6eaca94205bd2190dd5795c87d5d8f0e77ed2fd7/materialize/resources/resource_cluster_replica.go#L124

I didn't actually try this, but I suspect that this will lead to a syntax error, because `foo@bar` is not a valid identifier:

```hcl
resource "materialize_cluster" "example_cluster" {
  name = "foo@bar"
}
```

And I suspect you can construct classic SQL injection:

```hcl
resource "materialize_cluster" "example_cluster" {
  name = "\"; DROP DATABASE lol; --"
}
```

(SQL injection in this context isn't _really_ a security issue, because you're almost surely running Terraform on trusted input, but it's still a bad look!)

## Solution

Use the following two functions to escape all identifiers and strings before including them in SQL queries:

  * [`pgx.QuoteString`](https://pkg.go.dev/gopkg.in/jackc/pgx.v1#Connection.QuoteString)
  * [`pgx.QuoteIdentifier`](https://pkg.go.dev/gopkg.in/jackc/pgx.v1#Connection.QuoteIdentifier)

This is roughly equivalent to how the Snowflake Terraform provider works.

We should ensure that the tests for all resources have a test case with adversarial values for all parameters.

**Comment by benesch** [comment]
See also #28; the issue description assumes we're going to switch to pgx by recommending the pgx quoting functions. But lib/pq has equivalents, if for some reason we don't want to switch to pgx.

**Comment by bobbyiliev** [comment]
Just had a chat with @dehume about the [pgx.QuoteString](https://pkg.go.dev/gopkg.in/jackc/pgx.v1#Connection.QuoteString) and [pgx.QuoteIdentifier](https://pkg.go.dev/gopkg.in/jackc/pgx.v1#Connection.QuoteIdentifier) functions, as it like those aren't public [functions](https://github.com/jackc/pgx/issues/868), we can't use them directly in our statement builder logic.

Instead, what we could do is to cherry-pick them as both functions are very very simple, just a single line of string replace: 
> https://github.com/jackc/pgx/blob/4f67f16296bc/sanitize.go#L16-L26 ; 

This is the exact same approach that Snowflake is taking too:
> https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/snowflake/escaping.go#L11-L15

Let me know if you have any objections

**Comment by benesch** [comment]
Ah yeah good point. Just copy/pasting them into the repo sounds great.
