### ISSUE TITLE
Use pgx instead of lib/pq

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/terraform-provider-materialize#28]
From my and @mjibson's experience at Cockroach: we should use pgx instead of lib/pq. It's more reliable. 

@mjibson—pgx is still your recommendation, right?

It should be just as compatible with sqlx, and requires just a tiny change to go.mod and the connection string. See https://github.com/jackc/pgx/issues/81 for details.

**Comment by mjibson** [comment]
Yes, I still recommend pgx over lib/pq if pgx has the features you need (lib/pq does support a few obscure features that pgx does/did not).
