### ISSUE TITLE
Support `COMMENT` attribute

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#297]
Comments should be supported at the table, view and column level for objects.

**Comment by morsapaes** [comment]
This should wait for feature stabilization, in particular for [Materialize #21465](https://github.com/MaterializeInc/materialize/issues/21465) and [#21451](https://github.com/MaterializeInc/materialize/issues/21451).

**Comment by morsapaes** [comment]
Now that `COMMENT ON` has been implemented for all object types, it's safe to start working on this. @bobbyiliev @dehume The flag should be lifted in the next two weeks!
