### ISSUE TITLE
Use nested schemas

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/terraform-provider-materialize#30]
I noticed that we're using Terraform's map type to represent Kafka brokers:

https://github.com/MaterializeInc/terraform-provider-materialize/blob/e20b557841486c9ea2dfc6c845796669555db46f/materialize/resources/resource_connection.go#L169

but then reaching inside the map to pull out expected fields:

https://github.com/MaterializeInc/terraform-provider-materialize/blob/e20b557841486c9ea2dfc6c845796669555db46f/materialize/resources/resource_connection.go#L564-L588

This is going to fail with an ugly panic if a user typos a map field in their HCL.

A better approach is to use nested schemas inside of a list. See the `ordered_cache_behavior` field in the `aws_cloudfront_distribution` resource for an example: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution

```
resource "aws_cloudfront_distribution" "s3_distribution" {
  # Cache behavior with precedence 0
  ordered_cache_behavior {
    path_pattern     = "/content/immutable/*"
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD", "OPTIONS"]
    target_origin_id = local.s3_origin_id

    forwarded_values {
      query_string = false
      headers      = ["Origin"]

      cookies {
        forward = "none"
      }
    }

    min_ttl                = 0
    default_ttl            = 86400
    max_ttl                = 31536000
    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }

  # Cache behavior with precedence 1
  ordered_cache_behavior {
    path_pattern     = "/content/*"
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = local.s3_origin_id

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }
}
```

This allows Terraform's type checking to kick in, and filter out invalid fields, etc. 

Here's a similar example from the Frontegg provider that shows how this is implemented: https://github.com/frontegg/terraform-provider-frontegg/blob/9976fb90bb60aaa28fed945ee67aefb761bd8e23/provider/resource_frontegg_workspace.go#L544-L566

**Comment by bobbyiliev** [comment]
I've been stuck on this for a bit now, as soon as I change ` Elem:          &schema.Schema{Type: schema.TypeMap},` to a nested schema, I start hitting this error:

```
2023-02-23T17:54:22.975+0200 [ERROR] vertex "materialize_connection.example_kafka_connection" error: Unsupported argument
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 87, in resource "materialize_connection" "example_kafka_connection":
│   87:   kafka_brokers = [{
│ 
│ An argument named "kafka_brokers" is not expected here. 
```

The same argument is accepted just fine when using `TypeMap`.

Draft PR:

https://github.com/MaterializeInc/terraform-provider-materialize/pull/39

**Comment by bobbyiliev** [comment]
Will continue working on this after the refactor in #36

**Comment by benesch** [comment]
Right, the way you use nested resources is a little different! It's probably something like: 

```hcl
resource "materialize_connection" "example_kafka_connection" {
  name            = "example_kafka_connection"
  connection_type = "KAFKA"
  
  kafka_broker  {
      hostname = "abc"
  }

  kafka_broker  {
      hostname = "def"
  }
}
```

(I'd also just kill the `kafka_broker` vs `kafka_brokers`—in Terraform is equally ergonomic to just have `kafka_brokers`!)
