### ISSUE TITLE
Kafka source: support default `SSH TUNNEL` option

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/terraform-provider-materialize#357]
[Materialize #22799](https://github.com/MaterializeInc/materialize/pull/22799) introduced an option to define a default SSH connection for all brokers in a Kafka connection using the following syntax:

```sql
CREATE CONNECTION kafka_connection TO KAFKA (
    BROKER 'broker1:9092',
    SSH TUNNEL ssh_connection
);
```

The pre-existing syntax should now only be used to connect to multiple brokers when different SSH connections are used for each:

```sql
CREATE CONNECTION kafka_connection TO KAFKA (
BROKERS (
    'broker1:9092' USING SSH TUNNEL ssh1,
    'broker2:9092' USING SSH TUNNEL ssh2
    -- Add all Kafka brokers here. Connections to advertised brokers that are
    -- not listed here will not be tunneled.
    )
);
```

I'd double-check with @guswynn whether the top-level clause is also supported in the latter case, since this was a request in the original issue ([Materialize #18375](https://github.com/MaterializeInc/materialize/issues/18375)) and we might have just missed it in the documentation update ([Materilalize #22895](https://github.com/MaterializeInc/materialize/pull/22895/files)).

**Comment by benesch** [comment]
> supported in the latter case

Ah, like so? 

```sql
CREATE CONNECTION kafka_connection TO KAFKA (
    BROKERS (
    'broker1:9092' USING SSH TUNNEL ssh1,
    'broker2:9092' USING SSH TUNNEL ssh2
    -- Add all Kafka brokers here. Connections to advertised brokers that are
    -- not listed here will not be tunneled.
    ),
    SSH TUNNEL ssh3
);
```

And yep, that should be supported! I think the reference documentation does imply that this is supported? It just doesn't have an example of it specifically.

**Comment by morsapaes** [comment]
I started questioning the example with multiple SSH connections exactly because the documentation does suggest that it is supported, but then the default clause isn't used in the example (which is confusing to me, at least)!

**Comment by guswynn** [comment]
Yes its supported! also you can use `PRIVATELINK` on specific brokers and have a top-level for others (no idea why you would want that tho)
