### ISSUE TITLE
`schema_name` and `database_name` Not Applied to Postgres Subsources

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#389]
If a `schema_name` is used when creating a Postgres source
```
resource "materialize_source_postgres" "example_source_postgres_schema" {
  name          = "source_postgres_schema"
  schema_name   = materialize_schema.schema.name
  database_name = materialize_database.database.name
  size          = "3xsmall"
  publication   = "mz_source"
  schema        = ["PUBLIC"]

  postgres_connection {
    name          = materialize_connection_postgres.postgres_connection.name
    schema_name   = materialize_connection_postgres.postgres_connection.schema_name
    database_name = materialize_connection_postgres.postgres_connection.database_name
  }
}
```
The `schema_name` and `database_name` will be applied to the source:
```
SELECT schema_id  FROM mz_sources WHERE name = 'source_postgres_schema';
 schema_id
-----------
 u11
```
But not to the subsources:
```
SELECT schema_id FROM mz_sources WHERE type = 'subsource';
 schema_id
-----------
 u3
 u3
```
Note this applies to the Postgres source but not other sources

**Comment by dehume** [comment]
Most likely due to Terraform doing a `CREATE SOURCE <schema_name>.<source_name> ...` rather than `SET SCHEMA` so the current schema remains `materialize.public`.

**Comment by benesch** [comment]
This turned out to be a Materialize side bug! See https://github.com/MaterializeInc/materialize/issues/23557 and https://github.com/MaterializeInc/materialize/pull/23558. No action required here, unless there are integration tests that will now fail and need to be updated for the new behavior.

**Comment by dehume** [comment]
Closing in favor of a specific ticket to include testing around this for sources with subsources https://github.com/MaterializeInc/terraform-provider-materialize/issues/393
