### ISSUE TITLE
Replace mentions to `default` cluster with `quickstart`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/terraform-provider-materialize#425]
[Materialize #24019](https://github.com/MaterializeInc/materialize/pull/24019) renames the `default` cluster to `quickstart`. AFAICT, the provider relies on the `default` cluster for at least integration testing, so we should patch it accordingly.

**Comment by benesch** [comment]
@morsapaes I think @ParkMyCar handled this in https://github.com/MaterializeInc/terraform-provider-materialize/pull/423?

**Comment by morsapaes** [comment]
Err, yes. I even thanked him for it. 😴
