### ISSUE TITLE
MySQL Source: Add `ALTER SOURCE...ADD SUBSOURCES` once supported by Materialize

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/terraform-provider-materialize#490]

**Comment by morsapaes** [comment]
Linking to [Materialize #24975](https://github.com/MaterializeInc/materialize/issues/24975).

**Comment by morsapaes** [comment]
This is now supported. We're in the process of refactoring sources and subsources, so probably good to bring this up to parity with the PostgreSQL source resource before we make further changes, to avoid tech debt.

**Comment by bobbyiliev** [comment]
> This is now supported. We're in the process of refactoring sources and subsources, so probably good to bring this up to parity with the PostgreSQL source resource before we make further changes, to avoid tech debt.

Sounds like a plan!
