### ISSUE TITLE
[Epic] Terraform Cloud Resources

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#5]
Currently we are focusing on support for resources within the Materialize Database (SOURCES, SINKS, SECRETS...) but there are also resources in the cloud account not managed within the database (Enabling regions, User Passwords) which would need to be managed with some type of Public API. According to Joaquin we could do this with the MZ CLI.

**Comment by dehume** [comment]
Notion: https://www.notion.so/materialize/Terraform-Cloud-Resources-839b26be77b5493b8ad319f02769f4d2

**Comment by bobbyiliev** [comment]
I was able to use Joaquin’s VS Code and `mz` logic on how to use the HTTP auth via an app password and wrote a [little Golang script](https://gist.github.com/bobbyiliev/2a53dc79e60477f2bbf3c128cff61f2d) that we could use as a reference once we decide to start working on this epic.

**Comment by bobbyiliev** [comment]
This is now available in `v0.5.0` after the merge of the cloud resources refactor: https://github.com/MaterializeInc/terraform-provider-materialize/pull/351

Tasks that can be contributed separately in follow-up PRs:

- [ ]  Add the new Cloud Resources:
  - [ ]  `materialize_region`
- [ ]  Add the new data sources:
  - [ ]  `materialize_organization`
