### ISSUE TITLE
Bug: Kafka Source fails to apply with UPSERT envelope, VALUE FORMAT JSON

### ISSUE THREAD

**Issue by neo-will-parker** [MaterializeInc/terraform-provider-materialize#606]
Hi! My resource is defined like:

```
resource "materialize_source_kafka" "materialize_source" {
  cluster_name  = "general_purpose"
  database_name = "landing"
  envelope {
    upsert   =  true
  }
  key_format {
    text = true
  }
  value_format {
    json = true
  }
  kafka_connection {
    name          = "confluent"
    database_name = "landing"
    schema_name   = "data_infrastructure"
  }
  name        = "testingestionwill6"
  schema_name = "whodunnitService"
  topic       = "materialize.whodunnitService.testingestionwill6"
}
```

**Expected**: A source is created.

**Actual**: Plan is successful, but Apply fails with invalid SQL, i.e. no `VALUE FORMAT` clause.

```
CREATE SOURCE "landing"."whodunnitService"."testingestionwill6" IN CLUSTER "general_purpose" FROM KAFKA CONNECTION "landing"."data_infrastructure"."confluent" (TOPIC 'materialize.whodunnitService.testingestionwill6') KEY FORMAT TEXT ENVELOPE UPSERT;
```

Note this _does_ work correctly for `value_format {text = true}`

**Comment by benesch** [comment]
Thanks for the report, Will, and sorry about the bug! Looks straightforward to track down. @bobbyiliev—can you take a look when you're next online?

**Comment by bobbyiliev** [comment]
Thank you for reporting this @neo-will-parker very much appreciated!

I've just submitted a PR with a fix for the value format JSON in the Terraform query builder. Once merged we will cut a new release as soon as possible.
