### ISSUE TITLE
Bug: `materialize_connection_aws` resource read query not detecting all attributes

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/terraform-provider-materialize#629]
After creating an AWS connection using the `materialize_connection_aws` resource, there are no entries in the `mz_internal.mz_aws_connections`table.

https://github.com/MaterializeInc/terraform-provider-materialize/blob/183b8d8d5f1ee06d9e5c64e03a0725ae6aff2e05/pkg/materialize/connection_aws.go#L143-L175

We should investigate why this is happening and if the view name has changed or if this is an actual issue.

**Comment by benesch** [comment]
Linking in my comment about how to fix this here! https://github.com/MaterializeInc/terraform-provider-materialize/pull/627#discussion_r1711964889

**Comment by bobbyiliev** [comment]
Thanks @benesch! Just testing this now! Saw your comment too late after merging the PR.

**Comment by bobbyiliev** [comment]
The `mz_internal.mz_aws_connections` still seems to be empty evena after adding the flag, will need to look into this further.

**Comment by bobbyiliev** [comment]
Got it! Had to also add `--aws-connection-role-arn` and `--aws-account-id`.
