### ISSUE TITLE
Update go version above 1.20

### ISSUE THREAD

**Issue by kfollesdal** [MaterializeInc/terraform-provider-materialize#648]
### Feature request

We are building our terraform providers ourself. It would be nice if go version is update to a version above 1.20 fo better compatibility. Would make our building easier, noot needing to use 1.20 ;-)

Should be enough to run `go mod tidy` with an higher go version. 

https://go.dev/doc/go1.21#tools

**Comment by bobbyiliev** [comment]
Hey @kfollesdal 👋 

Thank you for this suggestion! I've just prepared a PR for this: https://github.com/MaterializeInc/terraform-provider-materialize/pull/649

**Comment by sjwiesman** [comment]
@kfollesdal. I'm just curious, why build the terraform provider yourself?

**Comment by kfollesdal** [comment]
@sjwiesman our environment is built on [NixOS/nixpkgs](https://nixos.org/). This give us easy management and control of dependency across our teams.
