### ISSUE TITLE
Sink `item_name` field should probably be called `from`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/terraform-provider-materialize#75]
To match the name in `CREATE SINK ... FROM`.

**Comment by benesch** [comment]
cc @bobbyiliev

**Comment by bobbyiliev** [comment]
I think that the main reasoning for going with `item_name` was the reference in the docs:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/21223421/225880374-f05f2358-f0f8-43a3-b13c-5e6e85d4b3dd.png">

@morsapaes @dehume Let me know what you think and I can submit a PR with the change!

**Comment by dehume** [comment]
> I think that the main reasoning for going with `item_name` was the reference in the docs:
 
Yeah. I went with that from the docs. Don't have very strong opinions on what the best terminology for it should be.

**Comment by benesch** [comment]
Ah, I see! The sink's "from" is how we talk about it internally:

https://github.com/MaterializeInc/materialize/blob/df276bc04a04482c5c8709e907a48f8c0c1d7974/src/sql-parser/src/ast/defs/statement.rs#L774-L785

The `item_name` there is more describing the _type_ of what you have to provide (an item/object name), rather than the name of the thing itself (the object _from_ which you're creating the sink).
