### ISSUE TITLE
Docs updates

### ISSUE THREAD

**Issue by tr0njavolta** [MaterializeInc/terraform-provider-materialize#92]
Creating an issue to track docs changes. 

- Clarify Usage section
- Review data source & resources for attributes & examples
- Tutorial style guide (not in this repo)

**Comment by dehume** [comment]
Does the Docs Team imagine most of the documentation for the provider will live in the Materialize repo or within the provider/registry itself?

**Comment by jseldess** [comment]
@tr0njavolta, now that we have a Terraform page in the docs, what are the other plans? Instead of one umbrella issue, it'd be best to break the work into more focused projects.

**Comment by dehume** [comment]
I think we can close this general issue and create more specific issues as they come up.
