### ISSUE TITLE
Terraform Pulumi Bridge

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#94]
Create a Pulumi provider from the Terraform provider using the bridge. This will ultimately exist in a separate repo.

https://github.com/pulumi/pulumi-terraform-bridge

**Comment by dehume** [comment]
Getting up to speed with on porting a provider to pulumi (This [video](https://www.youtube.com/watch?v=ZjTFaqMrYvY) was really helpful). Seems the best option is using the template repo https://github.com/pulumi/pulumi-tf-provider-boilerplate

**Comment by dehume** [comment]
https://github.com/MaterializeInc/pulumi-materialize

**Comment by benesch** [comment]
Let me know if you need any help! I and @antifuchs have done this for a few TF providers over the past two years.
